coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "**/*.tsx"
  - "src/action/action-builder.ts"
  - "src/action/action-error.ts"
  - "src/action/from-either.ts"
  - "src/action/hook.ts"
  - "src/action/middlewares/**"
  - "src/create-nextjs.ts"
  - "src/client-binder.tsx"
  - "src/with-client-binder.ts"
  - "src/layout/**"
  - "src/page/**"
  - "src/route/**"
  - "src/shared/**"
  - "src/i18n/**"

flags:
  unit:
    paths:
      - src/
    carryforward: true
