coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "**/*.tsx"

flags:
  unit:
    paths:
      - src/
    carryforward: true
